# This blank file is needed so that we can refer to //bazel:ink.bzl
# That seems weird! Shouldn't ink.bzl be mentioned in this BUILD file somehow?

# (There happens to be a top-level BUILD file so we could use //:bazel/ink.bzl,
# but ideally that BUILD file wouldn't exist. There should instead be a BUILD
# file in each subdirectory, but that doesn't work right now because the C#
# code isn't correctly split into assemblies. That's a design flaw in our C#
# code, not in Bazel.)
